{
 "title": "Smart Meter",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Aktueller Strombedarf",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Smart Meter Query Statistik",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "errors_total", "legendFormat": "Errors" },
    { "expr": "queries_total", "legendFormat": "Queries" }
   ]
  },
  {
   "title": "Stromverbrauch aktuell",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "pt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netzfrequenz",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    { "expr": "f", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netzspannung pro Phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    { "expr": "ua", "legendFormat": "UA" },
    { "expr": "ub", "legendFormat": "UB" },
    { "expr": "uc", "legendFormat": "UC" }
   ]
  },
  {
   "title": "Stromverbrauch Tag",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expr": "increase(impep[1h])", "legendFormat": "__auto" }
   ]
  }
 ]
}